version: '3.7'
services:
  palworld:
    image: lapin/palworld
    container_name: palworld-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/palworld/data
    ports:
      - 8211:8211/udp
    restart: always
