version: '3'
services:
  ark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/ark/data
    ports:
        - "7777:7777/udp"
        - "7778:7778/udp"
        - "27015:27015/udp"
    restart: always
