version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
        - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_USER: fivem
      MYSQL_PASSWORD: fivem
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  fivem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
        - "30110:30110/tcp"
        - "30110:30110/udp"
        - "30120:30120/tcp"
        - "30120:30120/udp"
        - "40125:40125"
    restart: always
volumes: